# Generated by Django 5.0 on 2024-04-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageApp', '0002_messages_delete_messsages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
