# Generated by Django 5.0.2 on 2024-03-01 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0002_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('message2', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=150)),
                ('ethereum', models.CharField(max_length=150)),
                ('tether_USDT', models.CharField(max_length=150)),
                ('ERC20_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepositAmount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('Network', models.CharField(blank=True, max_length=100, null=True)),
                ('Proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('No deposit', 'No Deposit'), ('Invalid', 'Invalid'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed'), ('Credited', 'Credited')], default='', max_length=50)),
                ('requestID', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('Confirmed', models.BooleanField(default=False)),
                ('not_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('phone', models.CharField(default='', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome {user.firstname}', max_length=100)),
                ('message', models.TextField(default='Thank you for joining us. Should you have any questions or concerns, kindly open a chat and an admin will be assigned to you.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='no data', max_length=100)),
                ('address', models.CharField(default='no data', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Checking', 'Checking'), ('Paid', 'Paid'), ('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved, Pending', 'Approved, Pending')], default='Checking', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('RequestID', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
