# Generated by Django 5.0.2 on 2024-03-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0003_termsandcondition_walletaddress_websitevisitors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='Welcome <django.db.models.query_utils.DeferredAttribute object at 0x0000020AD6F0CEF0>', max_length=100),
        ),
    ]
