# Generated by Django 5.0.2 on 2024-03-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0004_alter_notifications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='Welcome!!', max_length=100),
        ),
    ]
