# Generated by Django 5.0.2 on 2024-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0006_cryptocards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocards',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
