# Generated by Django 5.0.2 on 2024-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0008_alter_cryptocards_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocards',
            name='available_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cryptocards',
            name='card_status',
            field=models.CharField(choices=[('Not activated', 'Not activated'), ('Activated', 'Activated'), ('Blocked', 'Blocked')], default='Not activated', max_length=15),
        ),
    ]
