# Generated by Django 5.0.2 on 2024-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0009_cryptocards_available_amount_cryptocards_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocards',
            name='card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
