# Generated by Django 5.0.2 on 2024-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0014_paymentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='address',
            new_name='bitcoin_address',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='network',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='ethereum_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='usdt_ERC20_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='usdt_TRC20_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
