# Generated by Django 5.0.2 on 2024-03-04 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0016_remove_userprofile_withdrawal_pin_cryptocards_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocards',
            old_name='pin',
            new_name='card_pin',
        ),
    ]
