# Generated by Django 5.0.2 on 2024-03-05 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0020_alter_paymentdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ethereum_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('usdt_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ethereum_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('usdt_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
