# Generated by Django 5.0.2 on 2024-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0021_exchangerates_cryptobalances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobalances',
            name='bitcoin_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptobalances',
            name='ethereum_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cryptobalances',
            name='usdt_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
