# Generated by Django 5.0.2 on 2024-03-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0027_alter_paymentdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idme',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
