# Generated by Django 5.0.2 on 2024-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0029_alter_idme_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='AccountManager',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
