# Generated by Django 5.0.2 on 2024-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0030_userprofile_accountmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='AccountManager',
            field=models.CharField(blank=True, default='No assigned Trader', max_length=255, null=True),
        ),
    ]
