# Generated by Django 5.0.2 on 2024-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0032_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
