# Generated by Django 5.0.2 on 2024-04-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0034_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='is_verified',
            old_name='is_verified',
            new_name='verified',
        ),
    ]
