# Generated by Django 5.0.2 on 2024-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0035_rename_is_verified_is_verified_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='is_verified',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
