# Generated by Django 5.0.2 on 2024-04-04 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0036_is_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='is_verified',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
