# Generated by Django 5.0 on 2024-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progressiveApp', '0037_is_verified_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='Confirmed',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='not_confirmed',
        ),
        migrations.AddField(
            model_name='deposit',
            name='status_message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status_message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Checking', max_length=30),
        ),
    ]
